name = "ReadMatlabDocstrings"
uuid = "5ac41729-0616-47d0-b24e-40b588cdc0a8"
authors = ["okatsn <okatsn@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
