name = "ReadMatlabDocstrings"
uuid = "5ac41729-0616-47d0-b24e-40b588cdc0a8"
authors = ["okatsn <okatsn@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"

[compat]
julia = "1.10"

[extras]
CompatHelperLocal = "5224ae11-6099-4aaa-941d-3aab004bd678"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter", "CompatHelperLocal"]
